name:  Application Pipeline

on:
  push:
    paths:
      - 'app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [java, react, python]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 🐳 Docker Login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🐳 Build & Push Image
      - name: Build & Push Docker Image
        run: |
          IMAGE_NAME=${{ matrix.service }}-app

          docker build -t $IMAGE_NAME ./app/${{ matrix.service }}
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      # deploy to ec2 (ubuntu)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            SERVICE=${{ matrix.service }}
            IMAGE=${{ secrets.DOCKER_USERNAME }}/${SERVICE}-app:latest

            # Pull latest image
            docker pull $IMAGE

            # Stop old container (if running)
            docker stop $SERVICE || true
            docker rm $SERVICE || true

            # Run new container
            docker run -d \
              --name $SERVICE \
              -p 80:80 \
              $IMAGE
