name: Proxy Pipeline

on:
  push:
    paths:
      - 'proxy/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-proxy ./proxy

      - name: Run container (test)
        run: |
          docker run -d -p 8080:80 my-proxy

      - name: Deploy (example)
        run:  ssh -o StrictHostKeyChecking=no ubuntu@<EC2-IP> << 'EOF'

      # Go to your project folder
      cd ~/Team-Task

      # Get latest code
      git pull origin main

      # Stop old container
      docker stop my-proxy || true
      docker rm my-proxy || true

      # Build new docker image
      docker build -t my-proxy ./proxy

      # Run container
      docker run -d -p 80:80 --name my-proxy my-proxy

    EOF
